### ISSUE TITLE
HDFS Service Check

### ISSUE THREAD

**Issue by kpgtek** [TOSIT-IO/tdp-collection#153]

**Comment by rpignolet** [comment]
Add WEBHDFS check with `hdfs` command and `webhdfs` protocol for example.

**Comment by leopaul36** [comment]
Some relevant HDFS service checks:
- Try to put, cat and get a file in HDFS via RPC
- Try to put, cat and get a file in HDFS via WebHDFS 
- Perform a HDFS FSCK
