### ISSUE TITLE
hive: make the password hive_ms_db_password stored in hive_ms_credentials_store_path updatable

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-collection#180]
Currently, if we change the `hive_ms_db_password` without prior deletion of the `hive_ms_credentials_store_path` JCEKS file, it will not be re-created. We need to find a way to check if the passwords match and recreate the file if needed.

**Comment by rpignolet** [comment]
We should create an Ansible module to update JCEKS. Should be done for Ranger if needed.

**Comment by leopaul36** [comment]
> We should create an Ansible module to update JCEKS. Should be done for Ranger if needed.

I tried to take a look at this. [pyjks](https://pyjks.readthedocs.io/en/latest/) exists but does not allow to save new files in the JCEKS format.

I guess our options are:
- Delete the JCEKS and recreate it everytime. Not really a good Ansible practice but really simple to implement.
- Create a `decrypt_jceks` module to read the content of the JCEKS file if it already exists on the machine then delete and recreate if needed (if the decrypted property and its related tdp var are not the same).
- Create a `jceks_entry` module that would just be a wrapper around the `hadoop credential create` command + some use of [pyjks](https://pyjks.readthedocs.io/en/latest/) to decrypt an entry that already exists.

IMO option 2 is a good compromise.

**Comment by leopaul36** [comment]
We should try this first: https://github.com/TOSIT-IO/tdp-collection/issues/629

**Comment by rpignolet** [comment]
IMO option 2 but without use of [pyjks](https://pyjks.readthedocs.io/en/latest/). The Hadoop credential API is simple (https://hadoop.apache.org/docs/r3.1.1/hadoop-project-dist/hadoop-common/CredentialProviderAPI.html).
Commands are listed here https://hadoop.apache.org/docs/r3.1.1/hadoop-project-dist/hadoop-common/CommandsManual.html#credential:

- create
- delete
- list

With this 3 commands we can make an Ansible module for creating and updating JCEKS with idempotence.

**Comment by leopaul36** [comment]
> IMO option 2 but without use of [pyjks](https://pyjks.readthedocs.io/en/latest/). The Hadoop credential API is simple (https://hadoop.apache.org/docs/r3.1.1/hadoop-project-dist/hadoop-common/CredentialProviderAPI.html). Commands are listed here https://hadoop.apache.org/docs/r3.1.1/hadoop-project-dist/hadoop-common/CommandsManual.html#credential:
> 
>     * create
> 
>     * delete
> 
>     * list
> 
> 
> With this 3 commands we can make an Ansible module for creating and updating JCEKS with idempotence.

`list` does not decrypt the actual property but only gives its name.

For example:

```
hadoop credential list -provider jceks://file/etc/hive/conf.ms/hive.jceks

Listing aliases for CredentialProvider: jceks://file/etc/hive/conf.ms/hive.jceks
javax.jdo.option.connectionpassword
```

Also two JCEKS files created with the same alias / value do not have equal checksums

**Comment by rpignolet** [comment]
I tried with `keytool` and I can list alias:
```
# keytool -list -v -keystore /etc/hive/conf.ms/hive.jceks -storetype jceks
Enter keystore password:  
Keystore type: JCEKS
Keystore provider: SunJCE

Your keystore contains 1 entry

Alias name: javax.jdo.option.connectionpassword
Creation date: Jan 10, 2023
Entry type: SecretKeyEntry
```
But I can not display the secret. According to https://stackoverflow.com/questions/37487358/how-to-display-java-keystore-secretkeyentry-from-command-line
> You can't. `keytool` is designed to prevent extraction of private keys and secret keys.

I have the impression that no command allows to see the secret of a JCEKS, it is necessary to do a bit of Java to do it.

It is not possible with the Hadoop credential API to read the password in plain text generated by an Ansible template ?

**Comment by leopaul36** [comment]
What should we do about this ? We need to settle on something before I start working on https://github.com/TOSIT-IO/tdp-collection/issues/387.

From the tests and discussions above I think our only option is to delete / generate a new JCEKS file on every `config` run. We can do wrap this in a new `util` role for easier maintenance.

Do we all agree @rpignolet @gboutry @mehdibn @Nuttymoon  ?

**Comment by Nuttymoon** [comment]
I am ok with regenerating the JCEKS file every time. It keeps things simple.

**Comment by leopaul36** [comment]
Todo: Try with the `UserProvider`, see [docs](https://hadoop.apache.org/docs/r3.1.1/hadoop-project-dist/hadoop-common/CredentialProviderAPI.html).
