### ISSUE TITLE
Services and components check

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection#218]
A "check" is a playbook used to verify if a service or a component is working.

A "check" must retry multiple time in order to wait for the service or component to be up and working. We must add variable for retry in order to specify 0 if we want to only "check" and not wait.

- [x] #114 
- [x] #153 
- [x] #241 
- [x] #242
- [x] #243
- [x] #244

**Comment by kpgtek** [comment]
For port check, which method to use?

- Ansible ```wait_for``` module to check port connection
- ```nc``` command with Ansible ```retries...until``` condition
- Ansible ```list_ports_facts```module
- ```ss``` (or ```netstat```) command with Ansible ```retries...until``` condition
