### ISSUE TITLE
exporter: hardcoded jmx-exporter.jar leads to file not found

### ISSUE THREAD

**Issue by DanielJohnHarty** [TOSIT-IO/tdp-collection#234]
The tdp_vars_defaults file *tdp_vars_defaults/exporter/exporter.yml* includes a hardcoded value which leads to `Error opening zip file or JAR manifest missing : /opt/tdp/jmx-exporter/jmx-exporter.jar` error.

**Comment by nolimitkun** [comment]
Hi, it's not hardcoded, it's a link to jmx-exporter jar : 
```
cd /opt/tdp/jmx-exporter
ls -la
lrwxrwxrwx. 1 root root     57 Apr 11 10:06 jmx-exporter.jar -> /opt/tdp/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar
-rw-r--r--. 1 root root 469645 Apr 11 10:06 jmx_prometheus_javaagent-0.16.1.jar
```
where dose this error come from ?
