### ISSUE TITLE
Template zkCli.sh script with quorum address

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-collection#253]
In most tools, we template the client scripts with necessary parameters to facilitate usage.
We should do the same for the zkCli.sh script.

**Comment by kpgtek** [comment]
Besides templating ```zkCli.sh``` script, I decided to add variables for ```zookeeper``` server's ports in ```tdp_vars_defaults/hadoop.yml```, for example:
```
zookeeper_server_client_port: 2181
zookeeper_server_follower_port: 2888
zookeeper_server_election_port: 3888
```
I think it's more simple and avoiding to create new issue and PR for this.
