### ISSUE TITLE
Spark UI should not be configured with Knox URLs by default

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-collection#261]
https://github.com/TOSIT-IO/tdp-collection/pull/182 introduced `spark.ui.proxyBase /gateway/tdpldap/spark3history` breaks the Spark History Server Web UI:

![image](https://user-images.githubusercontent.com/12017342/167896431-bf84d9e3-f181-4d62-805e-ad05c38aed14.png)

Rewriting the URLs to Knox should not be the default behavior

**Comment by mehdibn** [comment]
already done for spark2: 
`  spark.ui.proxyBase: "{% if 'knox' in groups and groups['knox'] %}/gateway/tdpldap/sparkhistory{% endif %}"`

**Comment by leopaul36** [comment]
> already done for spark2: ` spark.ui.proxyBase: "{% if 'knox' in groups and groups['knox'] %}/gateway/tdpldap/sparkhistory{% endif %}"`

Missed this one! Thanks @mehdibn

**Comment by mehdibn** [comment]
@leopaul36 you are welcome :) !
