### ISSUE TITLE
MAPRED /run/hadoop/mapred directory not created on boot

### ISSUE THREAD

**Issue by DanielJohnHarty** [TOSIT-IO/tdp-collection#296]
The `/run/hadoop/mapred` dir is lost on restart and there is no mechanism to re-create it on boot. This stops `hadoop-mapred-jobhistoryserver` service from launching.

**Comment by rpignolet** [comment]
Yes this is an issue for multiple `run` directory we create inside the collection. I fixed it for HDFS and YARN in #12 but it is missing for all other services.
