### ISSUE TITLE
SPARK missing configuration options for driver to exectuor port-ranges

### ISSUE THREAD

**Issue by DanielJohnHarty** [TOSIT-IO/tdp-collection#324]
The configuration parameters which enable the control/restriction of the ports used for communication between Spark drivers and executors are missing from the `tdp_var_defaults/spark.spark.yml`and `tdp_vars_defaults/spark3/spark3.yml` files. 

This is the first Spark driver port attempted to be used on the launch of a Spark job:
* `spark.driver.port`

On failure to connect with the spark.driver.port, the port number will be incremented and retried up to this many times:
* `spark.port.maxRetries`

The port used by all block managers. It must be outside the range of spark.driver.port + spark.sport.maxRetries:
* `spark.blockManager.port` 

The default values for these are empty strings (no restriction).

 I think they should be included to facilitate port range management due to the prevalence of firewall and iptable restrictions in production environments.

[Spark configuration parameters](https://spark.apache.org/docs/latest/configuration.html)
[Discussion related to limiting this port range](https://community.cloudera.com/t5/Support-Questions/Spark-Jobs-failing-firewall-issue/td-p/219169)

**Comment by wdavidw** [comment]
Before review #325, could you elaborate why they should be included and how they facilitate port range management. Also, are those properties default value or not, in which file are they originally defined (update the PR with this information in the comments).

**Comment by DanielJohnHarty** [comment]
I've updated the description to include more details.
