### ISSUE TITLE
SOLR pid dir /var/run/ranger_solr not created on boot

### ISSUE THREAD

**Issue by DanielJohnHarty** [TOSIT-IO/tdp-collection#326]
The `/var/run/ranger_solr` pid dir is lost on a system reboot and there is no mechanism to create it again on boot. This leads to `solr` demon failing to launch and hive queries failing because of it.

**Comment by DanielJohnHarty** [comment]
The hive queries launched by the `ŧest-cluster-deployment.yml` playbook hung for a long time. I checked all the services and everything was running except for solr. I manually created the solr_pid_dir` with the appropriate ownership and the `test-cluster-deployment.yml`'s hive tests worked.

The only errors in the logs were related to the failed connection to solr (I think it was hive-server2 logs but I can't be sure and I wiped the cluster to test with the fix before making a PR).

**Comment by leopaul36** [comment]
We should investigate this more closely, the fact that a Ranger plugin cannot send its logs to solr should not be blocking for the underlying component.

**Comment by DanielJohnHarty** [comment]
Ok I'll reproduce the error and get some more info.

**Comment by rpignolet** [comment]
Closed with #508
