### ISSUE TITLE
Add Kafka

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection#333]
As discussed in [Add Kafka to TDP #27](https://github.com/orgs/TOSIT-IO/discussions/27), we will add Apache Kafka to TDP. This also implies adding a new dedicated ZooKeeper service.

Targeted versions are:
- Kafka ~~3.2~~ 2.8
- ZooKeeper ~~3.6.3~~ 3.5.9

**Comment by rpignolet** [comment]
Kafka must be an option, for example if we add an Ansible group `kafka_server` and if there is no host inside this group, the Kafka playbook should do nothing without error. Same for the dedicated ZooKeeper.

**Comment by Nuttymoon** [comment]
As discussed in #340, downgrading targeted Kafka to 2.x and ZooKeeper version accordingly.

**Comment by Nuttymoon** [comment]
Closing this issue as Kafka is moved to `tdp-collection-extras`. See [dicussion#27](https://github.com/orgs/TOSIT-IO/discussions/27)
