### ISSUE TITLE
ZooKeeper: YARN znodes should be protected

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection#335]
The YARN znodes are not protected by any ACLs and can be modified by any user with a valid Kerberos ticket:
- `/yarn-leader-election`
- `/rmstore` (used by YARN RM)

Based on Hortonworks [ZooKeeper ACLs Best Practices: YARN](https://docs.cloudera.com/HDPDocuments/HDP3/HDP-3.1.0/zookeeper-acls/content/zookeeper_acls_best_practices_yarn.html) the ACLs should be set as follow:
- `/yarn-leader-election`: `world:anyone:r`, `sasl:rm:rwcda`
- `/rmstore`: `world:anyone:r`, `sasl:rm:rwcda`

**Comment by rpignolet** [comment]
`/hbase`, `/hiveserver2`, `/hadoopha` are good.
