### ISSUE TITLE
Enable Hive impersonation as default

### ISSUE THREAD

**Issue by gonzaloetjo** [TOSIT-IO/tdp-collection#337]
Enable impersonation (`hive.server2.enable.doas = true`) to facilitate access to external tables (without having to rely on multiple ranger policies).

Reasons to favor external tables:
    - Convenient to organize data
    - Convenient to apply access rights (less ranger policies)
    - With the appearance of new table-formats, like Iceberg, Delta and Hudi,  HIve ACID has lost footing as a reason for favoring managed tables. 

With this change, managed tables will also be accessible to users by simply adding ranger access to `/warehouse/tablespace/external/hive` in hdfs.

On the other-side, if components like Sentry were added this change would become unnecessary.

Cheers,

**Comment by mehdibn** [comment]
This parameter `hive.server2.enable.doas` is by default set to `true`=> impersonation is by default enabled in TDP 
You can use `beeline_auto` from edge and check user via yarn-ui

**Comment by gonzaloetjo** [comment]
You are right. Closing and moving the changes to  getting-started as they are declared to false there. Thanks
