### ISSUE TITLE
How to configure multiple disks?

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#356]
Hi,
How to configure multiple disks? and racks?

Best regards

**Comment by mehdibn** [comment]
@taabich 
you can do it via specific vars of `hdfs` and `yarn` in your ansible configuration or in `tdp-collection/tdp_vars_default`.
For yarn, vars to change in yarn_site are ` yarn.nodemanager.local-dirs` and `yarn.nodemanager.log-dirs`
For hdfs, var to change in hdfs_site is `dfs.datanode.data.dir`

**Comment by rpignolet** [comment]
For `dfs.datanode.data.dir` multiple directories are supported with a recent PR but I don't know if other properties are working with multiple directories.

**Comment by taabich** [comment]
This issue is fixed by 457

**Comment by taabich** [comment]
This issue is fixed by 457
