### ISSUE TITLE
dag: move common properties from hadoop.yml to tdp_cluster.yml for better dag integration

### ISSUE THREAD

**Issue by mehdibn** [TOSIT-IO/tdp-collection#382]

**Comment by rpignolet** [comment]
Wait https://github.com/orgs/TOSIT-IO/discussions/49 before doing this issue.

**Comment by rpignolet** [comment]
As stated by https://github.com/orgs/TOSIT-IO/discussions/49 move common variables to `tdp_cluster.yml`.

Before doing it, need:

- [ ] #448
