### ISSUE TITLE
Hive Server 2 Web UI is not secured by SSL

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection#388]

**Comment by leopaul36** [comment]
I was wondering if we should not totally disable it. Do you have any utility for the HS2 web UI ?

**Comment by Nuttymoon** [comment]
I don't really have a use case in mind but why disable it if it is working?

**Comment by leopaul36** [comment]
> I don't really have a use case in mind but why disable it if it is working?

Just to keep things simple by removing something we don't use but I don't have a strong opinion on this. It's also probably using a very old JSP framework full of CVEs so I was thinking to disable if we don't have a use for it

**Comment by Nuttymoon** [comment]
We can disable it by default but not sure that we can completely remove it from Hive.

**Comment by leopaul36** [comment]
According to [this](https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/cm_mc_hive_webui.html), setting `hive.server2.webui.port` to 0 disables it

**Comment by leopaul36** [comment]
> > According to [this](https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/cm_mc_hive_webui.html), setting `hive.server2.webui.port` to 0 disables it
> 
> Yes but still people can switch `hive.server2.webui.port` to 1 and it will not be secured by SSL.

Yes properties to secure it are on the same docs

**Comment by Nuttymoon** [comment]
Gonna do a PR to disable it by default and to secure it nonetheless.
