### ISSUE TITLE
In several roles we use /tmp

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#412]
Hi,
In several roles we use /tmp, it is preferable to use ansible tempfile. Sometimes  /tmp could not exists or badly reseized

Best regards

**Comment by taabich** [comment]
the flow roles are used /tmp
spark
hive
hbase

**Comment by kpgtek** [comment]
As it is mentioned in this issue, we should apply these changes only for binaries to be uploaded to remote ```/tmp```, and this should be concerned for ```roles```.
But ```/tmp``` is also used for other files, for example ```playbooks/tests/test_user_group.yml``` uses ```/tmp``` for ```ldif``` files. Should we also apply theses changes?

**Comment by kpgtek** [comment]
For this particular upload file use, could we name the variable to ```{{ upload_tmp_dir }}```?

**Comment by rpignolet** [comment]
Ignore `playbooks/tests/test_user_group.yml`, the issue is for archives uploaded like Hadoop, Hive, HBase, etc.
