### ISSUE TITLE
Add Ranger Solr in the tdp-lib DAG

### ISSUE THREAD

**Issue by ChristopheLRTE** [TOSIT-IO/tdp-collection#426]
Hello,

We found that the Solr installation, initialization and startup playbooks for Ranger have been removed (in the playbook /playbooks/meta/ranger.yml since this [commit](https://github.com/TOSIT-IO/tdp-collection/commit/34369291f13f6620fef110681f748f2c60baf0fc)).
Is Solr installed elsewhere or has it been removed (we don't find it anywhere else) ?

Thank you for your help !
C.L.

**Comment by rpignolet** [comment]
The first to open the PR wins :)

No one is assigned so to me that means no one is on it. You can do it if you want.
