### ISSUE TITLE
'zkCli.sh-command.j2 not found in zookeeper/client/templates

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#439]
Hi,  
there is a regression on the templates:
Could not find or access 'zkCli.sh-command.j2'
    Searched in:
            /home/tdp00/playbooks/ansible-manage-cluster/ansible_roles/collections/ansible_collections/tosit/tdp/roles/zookeeper/client/templates/zkCli.sh-command.j2
Best regards

**Comment by gboutry** [comment]
Hello @taabich,

`tdp/roles/zookeeper/client/templates` is a symlink to `tdp/roles/zookeeper/common/templates`

And as you can see here: https://github.com/TOSIT-IO/tdp-collection/blob/b4e4c811b141b0505f8a59f8137d8beb28105a0d/roles/zookeeper/common/templates/zkCli.sh-command.j2. At the latest commit, the file is still present in the file tree.

This means, there is an issue on your, and should check if everything is in order.

**Comment by leopaul36** [comment]
I think @Edouard-R had the same issue, it was because the roles were mounted from a Windows path. I don't know if Windows handles well the symlinks at the `git pull` phase.

**Comment by Edouard-R** [comment]
Exactly.
Had the same issue when running a VM Linux box, using a shared Windows folder.
I solved the issue by deleting all the "templates" links and copy/pasted the correct folder.
Regards
