### ISSUE TITLE
Copy from directory files

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#441]
Hi,
In the first : the most component installs use the ansible copy function from the files directory to the remote machine, That  obliges us to have symbolic links to directory file
Exemple:

- name: Upload {{ hive_dist_file }}
  copy:
    src: "files/{{ hive_dist_file }}"
    dest: /tmp
  
For the second: all copy is in /tmp when need to use ansible tmp directory

The best way is to us rpm package and install by ansible commande yum 
Best regards

**Comment by rpignolet** [comment]
Hi, RPM package is maybe better but Apache projects we use do not provide RPM packaging, they provide `.tar.gz` package. It is not plan to add RPM package inside TDP.

**Comment by taabich** [comment]
This fixed by 412
