### ISSUE TITLE
Dynamic name of cluster and managing disks

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#456]
- This issue is to manage disks for datanode, namenode
- This issue is to create à dynamique name of cluster

**Comment by rpignolet** [comment]
Please, open one issue for dynamic cluster name and another issue for manage multiple disks to have one PR for each feature. You can rename this issue for the first feature and create a new one for the second feature.

**Comment by taabich** [comment]
Split in 2 issues
