### ISSUE TITLE
Create a dynamique name of cluster

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#458]
This issue is to create a dynamique name of cluster

**Comment by taabich** [comment]
I would like to create a branch 458-dynmic-name-cluster but I'can. Please could we create a branch for me to work in it.

**Comment by rpignolet** [comment]
> I would like to create a branch 458-dynmic-name-cluster but I'can. Please could we create a branch for me to work in it.

Yes you must fork the repository and create branch inside your fork.
