### ISSUE TITLE
Trace ended with _resources in /tmp

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#477]
Hi,
When, I create  my cluster, I have a lot of trace in /tmp like:
hive      hadoop    6  4 oct.  08:39 61781270-9338-4cba-8069-109d6824434d_resources
hive      hadoop    6  4 oct.  08:40 41c006a8-5550-44f0-aa9f-d9a4e38d127e_resources
hive      hadoop    6  4 oct.  08:41 85f03b84-14a5-40f7-a782-e0271921b0ca_resources
hive      hadoop    6  4 oct.  08:42 9f4789ae-097e-4d68-b896-673be774b456_resources

Best regards

**Comment by rpignolet** [comment]
Hi @taabich, I know you want to help us but this issue does not help. Please, investigate why these files are created.

**Comment by nschung** [comment]
Hi @taabich,

These are the session resource directories. They are created when Hive CLI is used in mode non-interactive (ex with option -f, -e or with sparksql). 

Could you give us more information on how you use Hive pls? 

Best regards.

**Comment by rpignolet** [comment]
Close as answered.
