### ISSUE TITLE
Add "tdp-cluster" service in the DAG

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection#497]
In order to resolve https://github.com/TOSIT-IO/tdp-lib/issues/236, we should add a `tdp-cluster` service. In this service, we store all variables which are common to all services. This service must be a dependency for all component config in order to be restarted if the variables from `tdp-cluster` service are updated.

**Comment by gboutry** [comment]
Shouldn't we just add `tdp-cluster_config` to service configs ? That should take care of all the restarts no ?

**Comment by rpignolet** [comment]
> Shouldn't we just add `tdp-cluster_config` to service configs ? That should take care of all the restarts no ?

If a service config is `hdfs_config` for example, `hdfs_namenode_config` does not depends on `hdfs_config`, it is `hdfs_config` which depends on `hdfs_namenode_config` so `hdfs_namenode_config` is not a DAG children of `hdfs_config`. So if I add `tdp-cluster_config` to service configs, nothing will be restarted.

**Comment by gboutry** [comment]
Ok
