### ISSUE TITLE
Add Fluentbit agent configuration for log management

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection#613]
Like we did for Prometheus exporter, we should add a role to install, configure and start Fluentbit agent.

**Comment by mehdibn** [comment]
@rpignolet  we can close this issue ?

**Comment by rpignolet** [comment]
Closing since https://github.com/TOSIT-IO/tdp-collection-prerequisites/pull/63 won't be merged in favor of https://github.com/TOSIT-IO/tdp-observability/pull/24
