### ISSUE TITLE
Error related to template services

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-collection#624]
Hello,

For this services: ranger-admin, ranger-kms, spark-history and spark3-history we have an issue in theirs template services.
When we make a stop and after status it is marked failed.

I did an investigation on my side, I noticed
spark-history in the spark-history-server.service.j2 file, we must add SuccessExitStatus=143
for ranger-admin and ranger-kms in the following two files ranger-admin-services.sh.j2 and ranger-kms.j2
I removed ${JMX_OPTS} from the variable

JAVA_OPTS="  ${JAVA_OPTS}  ${JMX_OPTS} -XX:MetaspaceSize=100m -XX:MaxMetaspaceSize=200m -Xmx${ranger_admin_max_heap_size} -Xms1g -Xloggc:${XAPOLICYMGR_EWS_DIR}/logs/gc-worker.log -verbose: gc -XX:+PrintGCDetails "

and I no longer have the error, could you please confirm this correction?

Best Regards,

**Comment by leopaul36** [comment]
@YasmineZamni the issues have been fixed by #649 and #648
