### ISSUE TITLE
Try to replace JCEKS files by a PKCS#12

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-collection#629]
We are using JCEKS file to store some critical properties (ex: Hive MS db password).

We should try to use PKCS#12 files which are the new standard and easily manageable via Ansible.

**Comment by leopaul36** [comment]
Seems that this won't be possible...

The [Hadoop documentation](https://hadoop.apache.org/docs/r3.1.1/hadoop-project-dist/hadoop-common/CredentialProviderAPI.html) only mentions JCEKS files.

I tried with a PCKS12 file but it gave me a clear `Caused by: java.io.IOException: Invalid keystore format` error.

And we cannot go with JKS since this format apparently can not store entries of the `SecretKeyEntry` format:

```
Problem importing entry for alias javax.jdo.option.connectionpassword: java.security.KeyStoreException: Cannot store non-PrivateKeys.
```

It's also not possible to show the `SecretKeyEntry` with `keytool` or even with `openssl` after converting it to P12 according to [this](https://stackoverflow.com/questions/37487358/how-to-display-java-keystore-secretkeyentry-from-command-line).

**Comment by gboutry** [comment]
I thought we wanted to replace the JKS (java keystores / truststores) with PCKS#12, and not the JCEKS ?

**Comment by leopaul36** [comment]
> I thought we wanted to replace the JKS (java keystores / truststores) with PCKS#12, and not the JCEKS ?

Yes but the idea was also to find a replacement for JCEKS in order to solve this issue cleanly: https://github.com/TOSIT-IO/tdp-collection/issues/180

But I guess we won't have any other choice than recreate JCEKS files with every config run.

**Comment by gboutry** [comment]
Yes, but JCEKS are hadoop specific and cannot be replaced with a pcks#12 file.

JCEKS are only used for passwords and not truststores / keystores because it's meant to implement the Credential Provider api

**Comment by rpignolet** [comment]
Like @gboutry said, I think this issue cannot be done. For #180 we can make an Ansible module for updating JCEKS when needing with idempotence.

**Comment by leopaul36** [comment]
I agree that it's not possible, like I said in my first comment
