### ISSUE TITLE
hive installation fails because not enough heap memory

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-collection#638]
hive initiliazation fails because there's not enough heap memory to launch the command `hadoop version`.

```
fatal: [master-02]: FAILED! => changed=false
  cmd:
  - /opt/tdp/hive/bin/hive
  - --config
  - /etc/hive/conf.ms
  - --service
  - metaSchemaTool
  - -dbType
  - postgres
  - -validate
  delta: '0:00:00.258684'
  end: '2023-01-12 09:02:36.976660'
  failed_when_result: true
  msg: non-zero return code
  rc: 5
  start: '2023-01-12 09:02:36.717976'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Unable to determine Hadoop version information.
    'hadoop version' returned:
    Error occurred during initialization of VM Too small initial heap
  stdout_lines: <omitted
```

After investigation, it's because the default heapsize is set to `256` in hive config, and in PR #627 we removed the `m` at the end of the HADOOP_CLIENT_OPTS definition.

https://github.com/TOSIT-IO/tdp-collection/pull/627/files#diff-1731466729e9b8c19d86f0c29cb5e40cb933ee92bedb7f1032d6f2e536ee4230R69

**Comment by mehdibn** [comment]
@leopaul36 that's what i confirmed during the last meeting ;)

**Comment by gboutry** [comment]
What do you mean by "I confirmed during last meeting" ?
