### ISSUE TITLE
clear password in knox configuration

### ISSUE THREAD

**Issue by GuillaumeHold** [TOSIT-IO/tdp-collection#656]
In `/etc/knox/conf/topologies/tdpldap.xml ` there is a password in clear in the following property:
```
<param>
   <name>main.ldapRealm.contextFactory.systemPassword</name>
   <value>secret</value>
</param>
```
it might be possible to handle this with #387.

**Comment by atocharnaud** [comment]
Note that the file is readable by the world with the security it has after deploying knox.
