### ISSUE TITLE
Harcoded edge group in spark_kerberos_install

### ISSUE THREAD

**Issue by GuillaumeHold** [TOSIT-IO/tdp-collection#697]
If we avoid to deploy spark2, by removing the groups `spark`, `spark_hs`, `spark_client` from the inventory, the node `spark_kerberos_install` still execute.
The group `edge` is harcoded in the [playbook](https://github.com/TOSIT-IO/tdp-collection/blob/290d4b63e39d850c1a63c373a351ea4ffda630b1/playbooks/spark_kerberos_install.yml#L17) for the kerberos client.

The group should be `spark_client`.

**Comment by mehdibn** [comment]
As discussed, using `edge` will force the dependency between libs like for `spark_client` and `yarn_client`.
We must find a solution to resolve this sort of dependencies.
