### ISSUE TITLE
Variables from 'tdp_vars/' or 'tdp_vars_default/' always win precedence

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-collection#713]
> TLDR : we cannot override tdp_vars with `inventory/group_vars/all.yml`. It appears to be a bug from the `resolve` action plugin that only returns tdp_vars, ignoring the content of task_vars.

## Problem
Hi all, I used to use ansible group vars to overwride some variables used by tdp collections, but since I updated my git clones this behavior is not possible anymore. Let's say I want to change where hadoop logs are written, then I just have to override `hadoop_log_dir`, but where ? My first bet would be to declare it in `inventory/group_vars/all.yml` :
```yaml
# ./inventory/group_vars/all.yml
hadoop_log_dir: "my new value from inventory/group_vars/all.yml"
```
Here is my test play :
```yaml
- hosts: mynode
  tasks:
    # run resolve action plugin
    - tosit.tdp.resolve:
        node_name: hadoop_client
    # print hadoop_log_dir value
    - debug:
        var: hadoop_log_dir
```
Which results in :
```
TASK [debug] ***********************
ok: [mynode] => 
  hadoop_log_dir: /var/log/hadoop
```
No luck, my var hasn't been updated.  
If I declare my variable in `./tdp_vars/hadoop/hadoop.yml` and set `TDP_VARS=./tdp_vars` and rerun :
```yaml
# ./tdp_vars/hadoop/hadoop.yml
hadoop_log_dir: "hadoop_log_dir: my new value from ./tdp_vars/hadoop/hadoop.yml"
```
```
TASK [debug] ***********************
ok: [mynode] => 
  hadoop_log_dir: hadoop_log_dir: my new value from ./tdp_vars/hadoop/hadoop.yml
```
This time around, Ansible picked up the variable from `./tdp_vars/hadoop/hadoop.yml`. But to make sure my `inventory/group_vars/all.yml` file is actually read by Ansible, I comment the `tosit.tdp.resolve` action plugin call and rerun :
```yaml
- hosts: mynode
  tasks:
    # run resolve action plugin
    # - tosit.tdp.resolve:
    #     node_name: hadoop_client
    # print hadoop_log_dir value
    - debug:
        var: hadoop_log_dir
```
```
TASK [debug] ***********************
ok: [mynode] => 
  hadoop_log_dir: my new value from inventory/group_vars/all.yml
  ```
So Ansible is effectively reading my group_vars folder.

## Cause ?
I'm not sure but I think the issue is from `resolve.py` around here (https://github.com/TOSIT-IO/tdp-collection/blob/962586dab168b65d88b44253ce69243482b75a60/plugins/action/resolve.py#LL63-L74C22) :
```python
# Current node vars
vars = get_vars(task_vars, node_name)
# merge node vars with task vars, with task vars (hostvars/group vars) having
# precedence over tdp_vars
vars_merged_with_task_vars = merge_hash(vars, task_vars)

# Make merged variables available to template engine
self._templar.available_variables = vars_merged_with_task_vars
# Template the merged dict using ansible templating engine
result["ansible_facts"] = self._template_with_keys(vars)
result["changed"] = False
return result
```
Despite this comment saying "_merge node vars with task vars, with task vars (hostvars/group vars) having precedence over tdp_vars_", I think the following lines do not behave as intended as we only have access to the content of `tdp_vars` once the `resolve` action plugin is done working.

## Debugging
To better understand what the `resolve` plugin works with, I added 3 prints with `display.v()` :
```python
display.v(f"from task_vars: {task_vars['hadoop_log_dir']}")
display.v(f"from vars: {vars['hadoop_log_dir']}")
display.v(f"from vars_merged_with_task_vars: {vars_merged_with_task_vars['hadoop_log_dir']}")
```
And this is what I see when I run the play in verbose mode, with the plugin uncommented:
```
TASK [tosit.tdp.resolve] **************************
Node Name: hadoop_client
vars loaded: tdp_auto_hadoop
from task_vars: my new value from inventory/group_vars/all.yml
from vars: my new value from ./tdp_vars/hadoop/hadoop.yml
from vars_merged_with_task_vars: my new value from inventory/group_vars/all.yml
```
So we can see that at this time, the resolve plugin knows about my group_vars value, and that `vars_merged_with_task_vars` actually merged the variables giving precedence to `task_vars` so everything seems fine.  

I understand that the issued might be linked to how the templating is made in the last 3 lines, but the way it works is not clear to me.

I blindly tried to replace this line :
```diff
# Make merged variables available to template engine
self._templar.available_variables = vars_merged_with_task_vars
# Template the merged dict using ansible templating engine
-result["ansible_facts"] = self._template_with_keys(vars)
+result["ansible_facts"] = self._template_with_keys(vars_merged_with_task_vars)
```
But it gives me an error :
```
fatal: [mynode]: FAILED! => 
  msg: '''jmx_exporter_release'' is undefined'
```
## Conclusion
The only way to override variables that happen to be defined in collections's `tdp_vars_defaults/` folders seems to be by writing them in a similar tree behind `TDP_VARS`.  

Is there something I'm doing wrong or is this the expected behavior ?

Thanks for your work.

**Comment by rpignolet** [comment]
Variables in YAML files inside `TDP_VARS` tree are designed to be the variables set by users. If you want to override variables from `tdp_vars_defaults` you should put them inside `TDP_VARS` tree.

Ansible "classic" variables should not be used with TDP collections when they have `tdp_vars_defaults`.

The merge behavior between `tdp_vars` and Ansible variables is not well defined and we do not test it for now, we avoid set the same variable in Ansible variables and in `tdp_vars`.

**Comment by jusstol** [comment]
If TDP variables must be overridden by `TDP_VARS` only, what design would you recommend to reproduce what Ansible does with its group variables following some hierarchy ? If I have 3 environments, on 2 different platforms :
- platform1 :
  - prod
- platform2 :
  - staging
  - dev

With Ansible variables we can create 5 files, and define their relationship :
```
group_vars/
├── dev.yml
├── platform1.yml
├── platform2.yml
├── prod.yml
└── staging.yml
```
```ini
# hosts file

[platform1:children]
dev
staging

[platform2:children]
prod
```

Currently, `TDP_VARS` only accepts one path, but if we could provide multiple paths similarly to `TDP_COLLECTION_PATH`, we would be able to reproduce how Ansible treats groups with some sort of order of paths to lookup. This example would allow us to only define common parent environment variables in `my_vars/platform2/` for example, and child environment specific variables in `my_vars/dev/` that would take precedence as it is the last path :

```bash
export TDP_VARS=my_vars/platform2,my_vars/dev
```
Is it a good suggestion ? Or maybe there's already a way to achieve that ?

**Comment by rpignolet** [comment]
`tdp_vars` are not designed to manage multiple cluster, we made this choice when starting TDP Manager which manage `tdp_vars`.

You need one TDP Manager for each cluster you want with `tdp_vars` separate for each cluster.

TDP Manager can update `tdp_vars` with `tdp-lib` (Python API), with `tdp-server` (HTTP REST API), and with `tdp-ui` (UI interface over REST API). They only manage one `tdp_vars` tree, they can not manage multiple tree and we do not plan to add this feature currently.

**Comment by jusstol** [comment]
I understand that tdp_vars are designed for one cluster. All I want to do is to facilitate the way I store each of my clusters **initial** variables on my git repos. I want the **first** deployment on my `dev` environment to inheritate from `platform1` common values.

I think I found how to do just that. I tried to add fake collections in `TDP_COLLECTION_PATH` making sure they all have a `tdp_vars_defaults/` folder, leaving `TDP_VARS` with only one path. Example :
```
ansible_collections/
├── my_collections
│   ├── dev
│   │   └── tdp_vars_defaults
│   └── platform1
│       └── tdp_vars_defaults
└── tosit
    ├── tdp
    ├── tdp_extra
    ├── tdp_observability
    └── tdp_prerequisites
```
And :
```bash
# adding my collections at the end, platform1 then dev
export TDP_COLLECTION_PATH=ansible_collections/tosit/tdp:ansible_collections/tosit/tdp_extra:ansible_collections/tosit/tdp_observability:ansible_collections/my_collections/platform1/:ansible_collections/my_collections/dev/
```
First run declaring `hadoop_log_dir` only on platform1 :
```yaml
# content of ansible_collections/my_collections/platform1/tdp_vars_defaults/hadoop/hadoop.yml
hadoop_log_dir: "my var from platform1 collection"
```
```
TASK [debug] ************************
ok: [mynode] => 
  hadoop_log_dir: my var from platform1 collection
```
Second run adding the variable definition to dev :
```yaml
# content of ansible_collections/my_collections/platform1/tdp_vars_defaults/hadoop/hadoop.yml
hadoop_log_dir: "my var from platform1 collection"
```
```yaml
# content of ansible_collections/my_collections/dev/tdp_vars_defaults/hadoop/hadoop.yml
hadoop_log_dir: "my var from dev collection"
```
```
TASK [debug] ************************
ok: [mynode] => 
  hadoop_log_dir: my var from dev collection
```
Is it something you would discourage, or maybe encourage by introducing a new `MY_DEFAULTS_VARS` kind of intermediate list of paths to lookup ?

Thanks for you answers and your time!

**Comment by rpignolet** [comment]
You can do it but your `dev` environment will inheritate from `platform1` common values for **all** deployments not only the first one if variables are not defined in `tdp_vars`.

For example, `hadoop_log_dir` is defined in `dev` and `platform1` but not in `tdp_vars`, `dev` will win because this is the last in `TDP_COLLECTION_PATH`. If you deploy the cluster, then change `hadoop_log_dir` in `dev` and you run another deployment, the new value of `hadoop_log_dir` will be used.

Currently, when you run `tdp init` to initialize `tdp_vars`, all `tdp_vars_defaults` will be copied in `tdp_vars`. This behaviour will change soon to disable this copy and have in `tdp_vars` only user override.

`tdp reconfigure` look at `tdp_vars` git repository and compare it to commit recorded inside the database. If you do not update `tdp_vars`, `tdp reconfigure` can not reconfigure your cluster and restart only required services that depends on the configuration you change.

I think what you want is to specify multiple `overrides`, for example: `tdp init --overrides platform1:dev1`. This way you will have a `tdp_vars` init with your custom variables merged in the correct order. Currently `--overrides` only support one directory but I think we can support multiple directories.

**Comment by jusstol** [comment]
Thanks for your clear answer, I like the suggestion. Let's imagine this scenario :
- you already pushed the change where as you said, `tdp init` does not copy all `tdp_vars_defaults/` into the `tdp_vars/` folder anymore
- the `--overrides` parameter accepts multiple paths
- I do not add my platform1 and dev variables to `TDP_COLLECTION_PATH` and also leave `TDP_VARS` untouched.
- I run `tdp init --overrides platform1:dev`

Where will the result of the merge done by the last command go? Is it only in the sqlite database? Or will there be another folder that the `tdp_vars.py` inventory plugin would be aware of ? Making it so that `ansible-playbook` commands would know about the result of the merge done by `tdp init --overrides platform1:dev`. Or maybe it is planned that that plugin can directly read the content of the database.

I want to understand the best as I can what tdp 0.0.1 will look like, so that I can be prepared.

**Comment by rpignolet** [comment]
`tdp init --overrides platform1:dev` will merge and write variables inside `tdp_vars` tree defined with `TDP_VARS` environment variable. This is currently what `tdp init --overrides` does but with one directory.

The database does not record the content of `tdp_vars`, only git commit are recorded to know what version of `tdp_vars` are deployed. This is used for `tdp reconfigure` to know what services should be reconfigure and restarted.

`tdp_vars.py` inventory plugin look at `tdp_vars` and `tdp_vars_defaults` of each collection in `TDP_COLLECTION_PATH`.

**Comment by jusstol** [comment]
One last question.

> Currently, when you run `tdp init` to initialize `tdp_vars`, all `tdp_vars_defaults` will be copied in `tdp_vars`. _This behaviour will change soon to disable this copy and have in `tdp_vars` only user override._

So when the feature which copies all the variables from `tdp_vars_defaults/` dirs to `TDP_VARS` tree is deactivated, the result of `tdp init --overrides [MY_PATH]` will write in `TDP_VARS` only the variables defined in `[MY_PATH]` which differ from `tdp_vars_defaults/` dirs, not all the variables, is that correct ?

**Comment by rpignolet** [comment]
All variables from `[MY_PATH]` will be written in `TDP_VARS` without doing comparison with `tdp_vars_defaults`. If you want to set a variable in `TDP_VARS` with the exact same value as `tdp_vars_defaults` you can. This can be useful if you want to be sure that an update to the default variables doesn't change a specific variable.

**Comment by jusstol** [comment]
I'm closing this since variables from `tdp_vars/` and `tdp_vars_defaults/` directories taking precedence over Ansible `group_vars` is not a bug, but the expected behavior.

Thank you for all the additional informations.
