### ISSUE TITLE
Variabilize source directory for binaries to upload

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection#733]
Related to https://github.com/TOSIT-IO/tdp-collection/pull/722 which variabilize destination directory for binaries, we should create a variable for source directory because, in the getting started, we put symlink in every collection to have a single directory where we have all binaries.

Add `binaries_local_dir` with default value `"{{ lookup('env', 'PWD') }}/files"`.

Then we will remove symlink created here https://github.com/TOSIT-IO/tdp-getting-started/blob/746d5ebad6d7cf33ce9c4afb98a0ac58224e7d0d/scripts/setup.sh#L128.

**Comment by kpgtek** [comment]
Should we also update ```ARCHITECTURE.md```?
This is about ```The binaries should be available in the the `files/` directory.```.

Note: in this documentation, there are ```files/``` for certificates, Kerberos and binaries, are they the same?
