### ISSUE TITLE
Ports for concurrent spark driver should be open

### ISSUE THREAD

**Issue by GuillaumeHold** [TOSIT-IO/tdp-collection#772]
When submitting multiple spark jobs from the same node, the jobs crash due to closed ports by the firewall.

spark uses : 
- `spark.port.maxRetries: 499`
- `spark.driver.port: 53000`
- `spark.blockManager.port: 54000`

So the port range `53000-53499` and `54000-54499` should be open.

**Comment by KaidoKopli** [comment]
Once the issue https://github.com/TOSIT-IO/tdp-collection-extras/issues/145 is solved we will be in a position to test whether this issue can be closed.
