### ISSUE TITLE
Keystore and truststore permissions

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection#98]
# Definition

## Keystore

A Java keystore stores private key entries, certificates with public keys or just secret keys.

## Truststore

A truststore is the opposite – while a keystore typically holds onto certificates that identify us, a truststore holds onto certificates that identify others.
In Java, we use it to trust the third party we're about to communicate with.

# Usage

To use a keystore or truststore, i.e. read a private key or a certificate, a password is needed. The same password can be used to add privates keys and certificates i.e. modify the store.
The keystore or truststore is a file and Unix permission is still check in order to read or modify the store. For example if you have the password for modify the truststore but you do not have the write permission on the store file, you can not modify it.

When a service A want to communicate with service B, service A must have read access on the keystore for the private key which is use to authenticate and service A must verify the identity of service B and must have read access on the truststore for the public certificate (i.e. the CA) which has signed the certificate of service B.

# Permissions

- Only `root` have the write permission on the keystore, trustore and current directory, so write permission only for owner with `root` as owner.
- Keystore contains private key so only service which need to authenticate to other have the read permission on the keystore, so read permission only for owner and group.
- Truststore contains public certificates which are trusted so read permission for owner, group and other.

With the Unix style permission :
```
drwxr-xr-x  root  root    .
-rw-r-----  root  hadoop  keystore.jks
-rw-r--r--  root  root    truststore.jks
```

With these Unix permissions, you can not create or delete file in the directory.
For the keystore, with the password, if you are not in the `hadoop` group you can not read the private key and you can not add you own private key.
For the truststore, with the password, you can not add trusted certificates.

With correct Unix permissions, password for keystore and truststore are not critical.

**Comment by Nuttymoon** [comment]
@nschung are you working on implementing those permissions?
